#!/bin/bash/
update the  package index
sudo yum install -y

# install Apache HTTP Server
sudo yum install -y httpd

# start Apache HTTP Server
sudo service httpd start

sudo service httpd start
sudo chkconfig httpd on

# create the web page
echo "Welcome to page1" | sudo tee /var/www/html/index.html

Restart Apache to ensure all changes are applied
Sudo service httpd Restart
